version: '3.1'

services:
  db:
    container_name: db
    image: mariadb:10.11
    environment: 
      MYSQL_USER: fahr
      MYSQL_PASSWORD: 2222
    networks:
     - mynetwork
    volumes:
     - db_data:/var/lib/mysql


  phpadmin:
    image: phpmyadmin
    restart: always
    ports:  
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    networks:
      - mynetwork
    depends_on:
      - db
  
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
